# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from hindsight_client_api.models.peer_claim_origin import PeerClaimOrigin
from hindsight_client_api.models.peer_claim_status import PeerClaimStatus
from hindsight_client_api.models.peer_claim_type import PeerClaimType
from hindsight_client_api.models.peer_source import PeerSource
from typing import Optional, Set
from typing_extensions import Self

class PeerClaim(BaseModel):
    """
    Persisted atomic claim with explicit lifecycle and provenance.
    """ # noqa: E501
    id: StrictStr
    bank_id: StrictStr
    model_id: StrictStr
    observer_peer_id: StrictStr
    target_peer_id: StrictStr
    claim_type: PeerClaimType
    text: StrictStr
    status: PeerClaimStatus
    origin: PeerClaimOrigin
    confidence: Union[StrictFloat, StrictInt]
    locked: StrictBool
    provenance: StrictStr
    valid_from: datetime
    valid_until: datetime
    created_at: datetime
    updated_at: datetime
    sources: Optional[List[PeerSource]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "bank_id", "model_id", "observer_peer_id", "target_peer_id", "claim_type", "text", "status", "origin", "confidence", "locked", "provenance", "valid_from", "valid_until", "created_at", "updated_at", "sources"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PeerClaim from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sources (list)
        _items = []
        if self.sources:
            for _item_sources in self.sources:
                if _item_sources:
                    _items.append(_item_sources.to_dict())
            _dict['sources'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PeerClaim from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "bank_id": obj.get("bank_id"),
            "model_id": obj.get("model_id"),
            "observer_peer_id": obj.get("observer_peer_id"),
            "target_peer_id": obj.get("target_peer_id"),
            "claim_type": obj.get("claim_type"),
            "text": obj.get("text"),
            "status": obj.get("status"),
            "origin": obj.get("origin"),
            "confidence": obj.get("confidence"),
            "locked": obj.get("locked"),
            "provenance": obj.get("provenance"),
            "valid_from": obj.get("valid_from"),
            "valid_until": obj.get("valid_until"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "sources": [PeerSource.from_dict(_item) for _item in obj["sources"]] if obj.get("sources") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


