# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from hindsight_client_api.models.peer_correction_claim_draft import PeerCorrectionClaimDraft
from typing import Optional, Set
from typing_extensions import Self

class PeerCorrectionPlanInput(BaseModel):
    """
    Version-bound correction plan shown to the caller before any mutation.
    """ # noqa: E501
    claims: Optional[Annotated[List[PeerCorrectionClaimDraft], Field(min_length=1, max_length=16)]] = None
    supersede_claim_ids: Optional[Annotated[List[StrictStr], Field(max_length=32)]] = None
    reason: Annotated[str, Field(min_length=1, strict=True, max_length=4000)]
    correction_text: Annotated[str, Field(min_length=1, strict=True, max_length=4000)]
    base_model_version: Annotated[int, Field(strict=True, ge=1)]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["claims", "supersede_claim_ids", "reason", "correction_text", "base_model_version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PeerCorrectionPlanInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in claims (list)
        _items = []
        if self.claims:
            for _item_claims in self.claims:
                if _item_claims:
                    _items.append(_item_claims.to_dict())
            _dict['claims'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PeerCorrectionPlanInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "claims": [PeerCorrectionClaimDraft.from_dict(_item) for _item in obj["claims"]] if obj.get("claims") is not None else None,
            "supersede_claim_ids": obj.get("supersede_claim_ids"),
            "reason": obj.get("reason"),
            "correction_text": obj.get("correction_text"),
            "base_model_version": obj.get("base_model_version")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


