# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RetainPeerContext(BaseModel):
    """
    Explicit participant attribution carried through retain.  IDs may be either a peer's internal ``id`` or its bank-scoped ``external_id``. This metadata is declarative input; Hindsight does not infer speaker or subject identity from free-form text at the HTTP boundary.
    """ # noqa: E501
    observer_peer_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=512)]] = None
    speaker_peer_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=512)]] = None
    subject_peer_ids: Optional[Annotated[List[StrictStr], Field(max_length=64)]] = None
    participant_peer_ids: Optional[Annotated[List[StrictStr], Field(max_length=64)]] = None
    source_message_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=1024)]] = None
    session_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=1024)]] = None
    modality: Optional[StrictStr] = 'actual'
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["observer_peer_id", "speaker_peer_id", "subject_peer_ids", "participant_peer_ids", "source_message_id", "session_id", "modality"]

    @field_validator('modality')
    def modality_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['actual', 'hypothetical', 'fictional', 'quoted']):
            raise ValueError("must be one of enum values ('actual', 'hypothetical', 'fictional', 'quoted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetainPeerContext from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetainPeerContext from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "observer_peer_id": obj.get("observer_peer_id"),
            "speaker_peer_id": obj.get("speaker_peer_id"),
            "subject_peer_ids": obj.get("subject_peer_ids"),
            "participant_peer_ids": obj.get("participant_peer_ids"),
            "source_message_id": obj.get("source_message_id"),
            "session_id": obj.get("session_id"),
            "modality": obj.get("modality") if obj.get("modality") is not None else 'actual'
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


