/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the PeerUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerUpdate{}

// PeerUpdate Mutable peer fields; external_id remains the stable identity key.
type PeerUpdate struct {
	DisplayName *DisplayName1 `json:"display_name,omitempty"`
	Kind *Kind `json:"kind,omitempty"`
	Metadata *Metadata `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PeerUpdate PeerUpdate

// NewPeerUpdate instantiates a new PeerUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerUpdate() *PeerUpdate {
	this := PeerUpdate{}
	return &this
}

// NewPeerUpdateWithDefaults instantiates a new PeerUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerUpdateWithDefaults() *PeerUpdate {
	this := PeerUpdate{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *PeerUpdate) GetDisplayName() DisplayName1 {
	if o == nil || IsNil(o.DisplayName) {
		var ret DisplayName1
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerUpdate) GetDisplayNameOk() (*DisplayName1, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *PeerUpdate) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given DisplayName1 and assigns it to the DisplayName field.
func (o *PeerUpdate) SetDisplayName(v DisplayName1) {
	o.DisplayName = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *PeerUpdate) GetKind() Kind {
	if o == nil || IsNil(o.Kind) {
		var ret Kind
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerUpdate) GetKindOk() (*Kind, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *PeerUpdate) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given Kind and assigns it to the Kind field.
func (o *PeerUpdate) SetKind(v Kind) {
	o.Kind = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PeerUpdate) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerUpdate) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PeerUpdate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *PeerUpdate) SetMetadata(v Metadata) {
	o.Metadata = &v
}

func (o PeerUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerUpdate) UnmarshalJSON(data []byte) (err error) {
	varPeerUpdate := _PeerUpdate{}

	err = json.Unmarshal(data, &varPeerUpdate)

	if err != nil {
		return err
	}

	*o = PeerUpdate(varPeerUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "display_name")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerUpdate struct {
	value *PeerUpdate
	isSet bool
}

func (v NullablePeerUpdate) Get() *PeerUpdate {
	return v.value
}

func (v *NullablePeerUpdate) Set(val *PeerUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerUpdate(val *PeerUpdate) *NullablePeerUpdate {
	return &NullablePeerUpdate{value: val, isSet: true}
}

func (v NullablePeerUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


