/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerCorrectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerCorrectionRequest{}

// PeerCorrectionRequest Natural-language correction to interpret against the current directional model.
type PeerCorrectionRequest struct {
	Text string `json:"text"`
	AdditionalProperties map[string]interface{}
}

type _PeerCorrectionRequest PeerCorrectionRequest

// NewPeerCorrectionRequest instantiates a new PeerCorrectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerCorrectionRequest(text string) *PeerCorrectionRequest {
	this := PeerCorrectionRequest{}
	this.Text = text
	return &this
}

// NewPeerCorrectionRequestWithDefaults instantiates a new PeerCorrectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerCorrectionRequestWithDefaults() *PeerCorrectionRequest {
	this := PeerCorrectionRequest{}
	return &this
}

// GetText returns the Text field value
func (o *PeerCorrectionRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *PeerCorrectionRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *PeerCorrectionRequest) SetText(v string) {
	o.Text = v
}

func (o PeerCorrectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerCorrectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerCorrectionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerCorrectionRequest := _PeerCorrectionRequest{}

	err = json.Unmarshal(data, &varPeerCorrectionRequest)

	if err != nil {
		return err
	}

	*o = PeerCorrectionRequest(varPeerCorrectionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "text")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerCorrectionRequest struct {
	value *PeerCorrectionRequest
	isSet bool
}

func (v NullablePeerCorrectionRequest) Get() *PeerCorrectionRequest {
	return v.value
}

func (v *NullablePeerCorrectionRequest) Set(val *PeerCorrectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerCorrectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerCorrectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerCorrectionRequest(val *PeerCorrectionRequest) *NullablePeerCorrectionRequest {
	return &NullablePeerCorrectionRequest{value: val, isSet: true}
}

func (v NullablePeerCorrectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerCorrectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


