/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)


// ObserverPeerId struct for ObserverPeerId
type ObserverPeerId struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ObserverPeerId) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ObserverPeerId)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ObserverPeerId) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableObserverPeerId struct {
	value *ObserverPeerId
	isSet bool
}

func (v NullableObserverPeerId) Get() *ObserverPeerId {
	return v.value
}

func (v *NullableObserverPeerId) Set(val *ObserverPeerId) {
	v.value = val
	v.isSet = true
}

func (v NullableObserverPeerId) IsSet() bool {
	return v.isSet
}

func (v *NullableObserverPeerId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObserverPeerId(val *ObserverPeerId) *NullableObserverPeerId {
	return &NullableObserverPeerId{value: val, isSet: true}
}

func (v NullableObserverPeerId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObserverPeerId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


