/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerOperation{}

// PeerOperation Stable async-operation acknowledgement.
type PeerOperation struct {
	OperationId string `json:"operation_id"`
	Deduplicated *bool `json:"deduplicated,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PeerOperation PeerOperation

// NewPeerOperation instantiates a new PeerOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerOperation(operationId string) *PeerOperation {
	this := PeerOperation{}
	this.OperationId = operationId
	var deduplicated bool = false
	this.Deduplicated = &deduplicated
	return &this
}

// NewPeerOperationWithDefaults instantiates a new PeerOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerOperationWithDefaults() *PeerOperation {
	this := PeerOperation{}
	var deduplicated bool = false
	this.Deduplicated = &deduplicated
	return &this
}

// GetOperationId returns the OperationId field value
func (o *PeerOperation) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *PeerOperation) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *PeerOperation) SetOperationId(v string) {
	o.OperationId = v
}

// GetDeduplicated returns the Deduplicated field value if set, zero value otherwise.
func (o *PeerOperation) GetDeduplicated() bool {
	if o == nil || IsNil(o.Deduplicated) {
		var ret bool
		return ret
	}
	return *o.Deduplicated
}

// GetDeduplicatedOk returns a tuple with the Deduplicated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerOperation) GetDeduplicatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deduplicated) {
		return nil, false
	}
	return o.Deduplicated, true
}

// HasDeduplicated returns a boolean if a field has been set.
func (o *PeerOperation) HasDeduplicated() bool {
	if o != nil && !IsNil(o.Deduplicated) {
		return true
	}

	return false
}

// SetDeduplicated gets a reference to the given bool and assigns it to the Deduplicated field.
func (o *PeerOperation) SetDeduplicated(v bool) {
	o.Deduplicated = &v
}

func (o PeerOperation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operation_id"] = o.OperationId
	if !IsNil(o.Deduplicated) {
		toSerialize["deduplicated"] = o.Deduplicated
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operation_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerOperation := _PeerOperation{}

	err = json.Unmarshal(data, &varPeerOperation)

	if err != nil {
		return err
	}

	*o = PeerOperation(varPeerOperation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operation_id")
		delete(additionalProperties, "deduplicated")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerOperation struct {
	value *PeerOperation
	isSet bool
}

func (v NullablePeerOperation) Get() *PeerOperation {
	return v.value
}

func (v *NullablePeerOperation) Set(val *PeerOperation) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerOperation) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerOperation(val *PeerOperation) *NullablePeerOperation {
	return &NullablePeerOperation{value: val, isSet: true}
}

func (v NullablePeerOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


