/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerClaims type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerClaims{}

// PeerClaims Directional claim collection.
type PeerClaims struct {
	ObserverPeerId string `json:"observer_peer_id"`
	TargetPeerId string `json:"target_peer_id"`
	Items []PeerClaim `json:"items,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PeerClaims PeerClaims

// NewPeerClaims instantiates a new PeerClaims object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerClaims(observerPeerId string, targetPeerId string) *PeerClaims {
	this := PeerClaims{}
	this.ObserverPeerId = observerPeerId
	this.TargetPeerId = targetPeerId
	return &this
}

// NewPeerClaimsWithDefaults instantiates a new PeerClaims object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerClaimsWithDefaults() *PeerClaims {
	this := PeerClaims{}
	return &this
}

// GetObserverPeerId returns the ObserverPeerId field value
func (o *PeerClaims) GetObserverPeerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObserverPeerId
}

// GetObserverPeerIdOk returns a tuple with the ObserverPeerId field value
// and a boolean to check if the value has been set.
func (o *PeerClaims) GetObserverPeerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObserverPeerId, true
}

// SetObserverPeerId sets field value
func (o *PeerClaims) SetObserverPeerId(v string) {
	o.ObserverPeerId = v
}

// GetTargetPeerId returns the TargetPeerId field value
func (o *PeerClaims) GetTargetPeerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetPeerId
}

// GetTargetPeerIdOk returns a tuple with the TargetPeerId field value
// and a boolean to check if the value has been set.
func (o *PeerClaims) GetTargetPeerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetPeerId, true
}

// SetTargetPeerId sets field value
func (o *PeerClaims) SetTargetPeerId(v string) {
	o.TargetPeerId = v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PeerClaims) GetItems() []PeerClaim {
	if o == nil || IsNil(o.Items) {
		var ret []PeerClaim
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerClaims) GetItemsOk() ([]PeerClaim, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PeerClaims) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PeerClaim and assigns it to the Items field.
func (o *PeerClaims) SetItems(v []PeerClaim) {
	o.Items = v
}

func (o PeerClaims) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerClaims) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["observer_peer_id"] = o.ObserverPeerId
	toSerialize["target_peer_id"] = o.TargetPeerId
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerClaims) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"observer_peer_id",
		"target_peer_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerClaims := _PeerClaims{}

	err = json.Unmarshal(data, &varPeerClaims)

	if err != nil {
		return err
	}

	*o = PeerClaims(varPeerClaims)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "observer_peer_id")
		delete(additionalProperties, "target_peer_id")
		delete(additionalProperties, "items")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerClaims struct {
	value *PeerClaims
	isSet bool
}

func (v NullablePeerClaims) Get() *PeerClaims {
	return v.value
}

func (v *NullablePeerClaims) Set(val *PeerClaims) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerClaims) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerClaims) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerClaims(val *PeerClaims) *NullablePeerClaims {
	return &NullablePeerClaims{value: val, isSet: true}
}

func (v NullablePeerClaims) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerClaims) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


