/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerCorrectionPlanInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerCorrectionPlanInput{}

// PeerCorrectionPlanInput Version-bound correction plan shown to the caller before any mutation.
type PeerCorrectionPlanInput struct {
	Claims []PeerCorrectionClaimDraft `json:"claims,omitempty"`
	SupersedeClaimIds []string `json:"supersede_claim_ids,omitempty"`
	Reason string `json:"reason"`
	CorrectionText string `json:"correction_text"`
	BaseModelVersion int32 `json:"base_model_version"`
	AdditionalProperties map[string]interface{}
}

type _PeerCorrectionPlanInput PeerCorrectionPlanInput

// NewPeerCorrectionPlanInput instantiates a new PeerCorrectionPlanInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerCorrectionPlanInput(reason string, correctionText string, baseModelVersion int32) *PeerCorrectionPlanInput {
	this := PeerCorrectionPlanInput{}
	this.Reason = reason
	this.CorrectionText = correctionText
	this.BaseModelVersion = baseModelVersion
	return &this
}

// NewPeerCorrectionPlanInputWithDefaults instantiates a new PeerCorrectionPlanInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerCorrectionPlanInputWithDefaults() *PeerCorrectionPlanInput {
	this := PeerCorrectionPlanInput{}
	return &this
}

// GetClaims returns the Claims field value if set, zero value otherwise.
func (o *PeerCorrectionPlanInput) GetClaims() []PeerCorrectionClaimDraft {
	if o == nil || IsNil(o.Claims) {
		var ret []PeerCorrectionClaimDraft
		return ret
	}
	return o.Claims
}

// GetClaimsOk returns a tuple with the Claims field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerCorrectionPlanInput) GetClaimsOk() ([]PeerCorrectionClaimDraft, bool) {
	if o == nil || IsNil(o.Claims) {
		return nil, false
	}
	return o.Claims, true
}

// HasClaims returns a boolean if a field has been set.
func (o *PeerCorrectionPlanInput) HasClaims() bool {
	if o != nil && !IsNil(o.Claims) {
		return true
	}

	return false
}

// SetClaims gets a reference to the given []PeerCorrectionClaimDraft and assigns it to the Claims field.
func (o *PeerCorrectionPlanInput) SetClaims(v []PeerCorrectionClaimDraft) {
	o.Claims = v
}

// GetSupersedeClaimIds returns the SupersedeClaimIds field value if set, zero value otherwise.
func (o *PeerCorrectionPlanInput) GetSupersedeClaimIds() []string {
	if o == nil || IsNil(o.SupersedeClaimIds) {
		var ret []string
		return ret
	}
	return o.SupersedeClaimIds
}

// GetSupersedeClaimIdsOk returns a tuple with the SupersedeClaimIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerCorrectionPlanInput) GetSupersedeClaimIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SupersedeClaimIds) {
		return nil, false
	}
	return o.SupersedeClaimIds, true
}

// HasSupersedeClaimIds returns a boolean if a field has been set.
func (o *PeerCorrectionPlanInput) HasSupersedeClaimIds() bool {
	if o != nil && !IsNil(o.SupersedeClaimIds) {
		return true
	}

	return false
}

// SetSupersedeClaimIds gets a reference to the given []string and assigns it to the SupersedeClaimIds field.
func (o *PeerCorrectionPlanInput) SetSupersedeClaimIds(v []string) {
	o.SupersedeClaimIds = v
}

// GetReason returns the Reason field value
func (o *PeerCorrectionPlanInput) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *PeerCorrectionPlanInput) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *PeerCorrectionPlanInput) SetReason(v string) {
	o.Reason = v
}

// GetCorrectionText returns the CorrectionText field value
func (o *PeerCorrectionPlanInput) GetCorrectionText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CorrectionText
}

// GetCorrectionTextOk returns a tuple with the CorrectionText field value
// and a boolean to check if the value has been set.
func (o *PeerCorrectionPlanInput) GetCorrectionTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CorrectionText, true
}

// SetCorrectionText sets field value
func (o *PeerCorrectionPlanInput) SetCorrectionText(v string) {
	o.CorrectionText = v
}

// GetBaseModelVersion returns the BaseModelVersion field value
func (o *PeerCorrectionPlanInput) GetBaseModelVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BaseModelVersion
}

// GetBaseModelVersionOk returns a tuple with the BaseModelVersion field value
// and a boolean to check if the value has been set.
func (o *PeerCorrectionPlanInput) GetBaseModelVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseModelVersion, true
}

// SetBaseModelVersion sets field value
func (o *PeerCorrectionPlanInput) SetBaseModelVersion(v int32) {
	o.BaseModelVersion = v
}

func (o PeerCorrectionPlanInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerCorrectionPlanInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Claims) {
		toSerialize["claims"] = o.Claims
	}
	if !IsNil(o.SupersedeClaimIds) {
		toSerialize["supersede_claim_ids"] = o.SupersedeClaimIds
	}
	toSerialize["reason"] = o.Reason
	toSerialize["correction_text"] = o.CorrectionText
	toSerialize["base_model_version"] = o.BaseModelVersion

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerCorrectionPlanInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reason",
		"correction_text",
		"base_model_version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerCorrectionPlanInput := _PeerCorrectionPlanInput{}

	err = json.Unmarshal(data, &varPeerCorrectionPlanInput)

	if err != nil {
		return err
	}

	*o = PeerCorrectionPlanInput(varPeerCorrectionPlanInput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "claims")
		delete(additionalProperties, "supersede_claim_ids")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "correction_text")
		delete(additionalProperties, "base_model_version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerCorrectionPlanInput struct {
	value *PeerCorrectionPlanInput
	isSet bool
}

func (v NullablePeerCorrectionPlanInput) Get() *PeerCorrectionPlanInput {
	return v.value
}

func (v *NullablePeerCorrectionPlanInput) Set(val *PeerCorrectionPlanInput) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerCorrectionPlanInput) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerCorrectionPlanInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerCorrectionPlanInput(val *PeerCorrectionPlanInput) *NullablePeerCorrectionPlanInput {
	return &NullablePeerCorrectionPlanInput{value: val, isSet: true}
}

func (v NullablePeerCorrectionPlanInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerCorrectionPlanInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


