/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the PeerModelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerModelRequest{}

// PeerModelRequest Request body for model/rebuild; claims are optional supplied evidence proposals.
type PeerModelRequest struct {
	Claims []PeerClaimDraft `json:"claims,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PeerModelRequest PeerModelRequest

// NewPeerModelRequest instantiates a new PeerModelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerModelRequest() *PeerModelRequest {
	this := PeerModelRequest{}
	return &this
}

// NewPeerModelRequestWithDefaults instantiates a new PeerModelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerModelRequestWithDefaults() *PeerModelRequest {
	this := PeerModelRequest{}
	return &this
}

// GetClaims returns the Claims field value if set, zero value otherwise.
func (o *PeerModelRequest) GetClaims() []PeerClaimDraft {
	if o == nil || IsNil(o.Claims) {
		var ret []PeerClaimDraft
		return ret
	}
	return o.Claims
}

// GetClaimsOk returns a tuple with the Claims field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerModelRequest) GetClaimsOk() ([]PeerClaimDraft, bool) {
	if o == nil || IsNil(o.Claims) {
		return nil, false
	}
	return o.Claims, true
}

// HasClaims returns a boolean if a field has been set.
func (o *PeerModelRequest) HasClaims() bool {
	if o != nil && !IsNil(o.Claims) {
		return true
	}

	return false
}

// SetClaims gets a reference to the given []PeerClaimDraft and assigns it to the Claims field.
func (o *PeerModelRequest) SetClaims(v []PeerClaimDraft) {
	o.Claims = v
}

func (o PeerModelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerModelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Claims) {
		toSerialize["claims"] = o.Claims
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerModelRequest) UnmarshalJSON(data []byte) (err error) {
	varPeerModelRequest := _PeerModelRequest{}

	err = json.Unmarshal(data, &varPeerModelRequest)

	if err != nil {
		return err
	}

	*o = PeerModelRequest(varPeerModelRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "claims")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerModelRequest struct {
	value *PeerModelRequest
	isSet bool
}

func (v NullablePeerModelRequest) Get() *PeerModelRequest {
	return v.value
}

func (v *NullablePeerModelRequest) Set(val *PeerModelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerModelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerModelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerModelRequest(val *PeerModelRequest) *NullablePeerModelRequest {
	return &NullablePeerModelRequest{value: val, isSet: true}
}

func (v NullablePeerModelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerModelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


