/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerCreate{}

// PeerCreate Request to create one bank-scoped peer identity.
type PeerCreate struct {
	ExternalId string `json:"external_id"`
	DisplayName *DisplayName1 `json:"display_name,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PeerCreate PeerCreate

// NewPeerCreate instantiates a new PeerCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerCreate(externalId string) *PeerCreate {
	this := PeerCreate{}
	this.ExternalId = externalId
	var kind string = "person"
	this.Kind = &kind
	return &this
}

// NewPeerCreateWithDefaults instantiates a new PeerCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerCreateWithDefaults() *PeerCreate {
	this := PeerCreate{}
	var kind string = "person"
	this.Kind = &kind
	return &this
}

// GetExternalId returns the ExternalId field value
func (o *PeerCreate) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *PeerCreate) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *PeerCreate) SetExternalId(v string) {
	o.ExternalId = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *PeerCreate) GetDisplayName() DisplayName1 {
	if o == nil || IsNil(o.DisplayName) {
		var ret DisplayName1
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerCreate) GetDisplayNameOk() (*DisplayName1, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *PeerCreate) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given DisplayName1 and assigns it to the DisplayName field.
func (o *PeerCreate) SetDisplayName(v DisplayName1) {
	o.DisplayName = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *PeerCreate) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerCreate) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *PeerCreate) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *PeerCreate) SetKind(v string) {
	o.Kind = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PeerCreate) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerCreate) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PeerCreate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *PeerCreate) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o PeerCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["external_id"] = o.ExternalId
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"external_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerCreate := _PeerCreate{}

	err = json.Unmarshal(data, &varPeerCreate)

	if err != nil {
		return err
	}

	*o = PeerCreate(varPeerCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "external_id")
		delete(additionalProperties, "display_name")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerCreate struct {
	value *PeerCreate
	isSet bool
}

func (v NullablePeerCreate) Get() *PeerCreate {
	return v.value
}

func (v *NullablePeerCreate) Set(val *PeerCreate) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerCreate) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerCreate(val *PeerCreate) *NullablePeerCreate {
	return &NullablePeerCreate{value: val, isSet: true}
}

func (v NullablePeerCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


