/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// PeerClaimType Taxonomy allowed in the compact peer card.
type PeerClaimType string

// List of PeerClaimType
const (
	PeerClaimTypeIdentity PeerClaimType = "IDENTITY"
	PeerClaimTypeAttribute PeerClaimType = "ATTRIBUTE"
	PeerClaimTypeRelationship PeerClaimType = "RELATIONSHIP"
	PeerClaimTypeInstruction PeerClaimType = "INSTRUCTION"
)

// All allowed values of PeerClaimType enum
var AllowedPeerClaimTypeEnumValues = []PeerClaimType{
	"IDENTITY",
	"ATTRIBUTE",
	"RELATIONSHIP",
	"INSTRUCTION",
}

func (v *PeerClaimType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PeerClaimType(value)
	for _, existing := range AllowedPeerClaimTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PeerClaimType", value)
}

// NewPeerClaimTypeFromValue returns a pointer to a valid PeerClaimType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPeerClaimTypeFromValue(v string) (*PeerClaimType, error) {
	ev := PeerClaimType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PeerClaimType: valid values are %v", v, AllowedPeerClaimTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PeerClaimType) IsValid() bool {
	for _, existing := range AllowedPeerClaimTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PeerClaimType value
func (v PeerClaimType) Ptr() *PeerClaimType {
	return &v
}

type NullablePeerClaimType struct {
	value *PeerClaimType
	isSet bool
}

func (v NullablePeerClaimType) Get() *PeerClaimType {
	return v.value
}

func (v *NullablePeerClaimType) Set(val *PeerClaimType) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerClaimType) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerClaimType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerClaimType(val *PeerClaimType) *NullablePeerClaimType {
	return &NullablePeerClaimType{value: val, isSet: true}
}

func (v NullablePeerClaimType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerClaimType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

