/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)


// SessionId struct for SessionId
type SessionId struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SessionId) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SessionId)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *SessionId) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableSessionId struct {
	value *SessionId
	isSet bool
}

func (v NullableSessionId) Get() *SessionId {
	return v.value
}

func (v *NullableSessionId) Set(val *SessionId) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionId) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionId(val *SessionId) *NullableSessionId {
	return &NullableSessionId{value: val, isSet: true}
}

func (v NullableSessionId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


