/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerCorrectionClaimDraft type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerCorrectionClaimDraft{}

// PeerCorrectionClaimDraft One stable claim proposed by the semantic correction planner.
type PeerCorrectionClaimDraft struct {
	ClaimType PeerClaimType `json:"claim_type"`
	Text string `json:"text"`
	Confidence *float32 `json:"confidence,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PeerCorrectionClaimDraft PeerCorrectionClaimDraft

// NewPeerCorrectionClaimDraft instantiates a new PeerCorrectionClaimDraft object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerCorrectionClaimDraft(claimType PeerClaimType, text string) *PeerCorrectionClaimDraft {
	this := PeerCorrectionClaimDraft{}
	this.ClaimType = claimType
	this.Text = text
	var confidence float32 = 1.0
	this.Confidence = &confidence
	return &this
}

// NewPeerCorrectionClaimDraftWithDefaults instantiates a new PeerCorrectionClaimDraft object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerCorrectionClaimDraftWithDefaults() *PeerCorrectionClaimDraft {
	this := PeerCorrectionClaimDraft{}
	var confidence float32 = 1.0
	this.Confidence = &confidence
	return &this
}

// GetClaimType returns the ClaimType field value
func (o *PeerCorrectionClaimDraft) GetClaimType() PeerClaimType {
	if o == nil {
		var ret PeerClaimType
		return ret
	}

	return o.ClaimType
}

// GetClaimTypeOk returns a tuple with the ClaimType field value
// and a boolean to check if the value has been set.
func (o *PeerCorrectionClaimDraft) GetClaimTypeOk() (*PeerClaimType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClaimType, true
}

// SetClaimType sets field value
func (o *PeerCorrectionClaimDraft) SetClaimType(v PeerClaimType) {
	o.ClaimType = v
}

// GetText returns the Text field value
func (o *PeerCorrectionClaimDraft) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *PeerCorrectionClaimDraft) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *PeerCorrectionClaimDraft) SetText(v string) {
	o.Text = v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *PeerCorrectionClaimDraft) GetConfidence() float32 {
	if o == nil || IsNil(o.Confidence) {
		var ret float32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerCorrectionClaimDraft) GetConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *PeerCorrectionClaimDraft) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float32 and assigns it to the Confidence field.
func (o *PeerCorrectionClaimDraft) SetConfidence(v float32) {
	o.Confidence = &v
}

func (o PeerCorrectionClaimDraft) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerCorrectionClaimDraft) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["claim_type"] = o.ClaimType
	toSerialize["text"] = o.Text
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerCorrectionClaimDraft) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"claim_type",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerCorrectionClaimDraft := _PeerCorrectionClaimDraft{}

	err = json.Unmarshal(data, &varPeerCorrectionClaimDraft)

	if err != nil {
		return err
	}

	*o = PeerCorrectionClaimDraft(varPeerCorrectionClaimDraft)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "claim_type")
		delete(additionalProperties, "text")
		delete(additionalProperties, "confidence")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerCorrectionClaimDraft struct {
	value *PeerCorrectionClaimDraft
	isSet bool
}

func (v NullablePeerCorrectionClaimDraft) Get() *PeerCorrectionClaimDraft {
	return v.value
}

func (v *NullablePeerCorrectionClaimDraft) Set(val *PeerCorrectionClaimDraft) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerCorrectionClaimDraft) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerCorrectionClaimDraft) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerCorrectionClaimDraft(val *PeerCorrectionClaimDraft) *NullablePeerCorrectionClaimDraft {
	return &NullablePeerCorrectionClaimDraft{value: val, isSet: true}
}

func (v NullablePeerCorrectionClaimDraft) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerCorrectionClaimDraft) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


