/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the PeerClaim type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerClaim{}

// PeerClaim Persisted atomic claim with explicit lifecycle and provenance.
type PeerClaim struct {
	Id string `json:"id"`
	BankId string `json:"bank_id"`
	ModelId string `json:"model_id"`
	ObserverPeerId string `json:"observer_peer_id"`
	TargetPeerId string `json:"target_peer_id"`
	ClaimType PeerClaimType `json:"claim_type"`
	Text string `json:"text"`
	Status PeerClaimStatus `json:"status"`
	Origin PeerClaimOrigin `json:"origin"`
	Confidence float32 `json:"confidence"`
	Locked bool `json:"locked"`
	Provenance Provenance `json:"provenance"`
	ValidFrom ValidFrom `json:"valid_from"`
	ValidUntil ValidUntil `json:"valid_until"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Sources []PeerSource `json:"sources,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PeerClaim PeerClaim

// NewPeerClaim instantiates a new PeerClaim object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerClaim(id string, bankId string, modelId string, observerPeerId string, targetPeerId string, claimType PeerClaimType, text string, status PeerClaimStatus, origin PeerClaimOrigin, confidence float32, locked bool, provenance Provenance, validFrom ValidFrom, validUntil ValidUntil, createdAt time.Time, updatedAt time.Time) *PeerClaim {
	this := PeerClaim{}
	this.Id = id
	this.BankId = bankId
	this.ModelId = modelId
	this.ObserverPeerId = observerPeerId
	this.TargetPeerId = targetPeerId
	this.ClaimType = claimType
	this.Text = text
	this.Status = status
	this.Origin = origin
	this.Confidence = confidence
	this.Locked = locked
	this.Provenance = provenance
	this.ValidFrom = validFrom
	this.ValidUntil = validUntil
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewPeerClaimWithDefaults instantiates a new PeerClaim object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerClaimWithDefaults() *PeerClaim {
	this := PeerClaim{}
	return &this
}

// GetId returns the Id field value
func (o *PeerClaim) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PeerClaim) SetId(v string) {
	o.Id = v
}

// GetBankId returns the BankId field value
func (o *PeerClaim) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *PeerClaim) SetBankId(v string) {
	o.BankId = v
}

// GetModelId returns the ModelId field value
func (o *PeerClaim) GetModelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModelId
}

// GetModelIdOk returns a tuple with the ModelId field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetModelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelId, true
}

// SetModelId sets field value
func (o *PeerClaim) SetModelId(v string) {
	o.ModelId = v
}

// GetObserverPeerId returns the ObserverPeerId field value
func (o *PeerClaim) GetObserverPeerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObserverPeerId
}

// GetObserverPeerIdOk returns a tuple with the ObserverPeerId field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetObserverPeerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObserverPeerId, true
}

// SetObserverPeerId sets field value
func (o *PeerClaim) SetObserverPeerId(v string) {
	o.ObserverPeerId = v
}

// GetTargetPeerId returns the TargetPeerId field value
func (o *PeerClaim) GetTargetPeerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetPeerId
}

// GetTargetPeerIdOk returns a tuple with the TargetPeerId field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetTargetPeerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetPeerId, true
}

// SetTargetPeerId sets field value
func (o *PeerClaim) SetTargetPeerId(v string) {
	o.TargetPeerId = v
}

// GetClaimType returns the ClaimType field value
func (o *PeerClaim) GetClaimType() PeerClaimType {
	if o == nil {
		var ret PeerClaimType
		return ret
	}

	return o.ClaimType
}

// GetClaimTypeOk returns a tuple with the ClaimType field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetClaimTypeOk() (*PeerClaimType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClaimType, true
}

// SetClaimType sets field value
func (o *PeerClaim) SetClaimType(v PeerClaimType) {
	o.ClaimType = v
}

// GetText returns the Text field value
func (o *PeerClaim) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *PeerClaim) SetText(v string) {
	o.Text = v
}

// GetStatus returns the Status field value
func (o *PeerClaim) GetStatus() PeerClaimStatus {
	if o == nil {
		var ret PeerClaimStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetStatusOk() (*PeerClaimStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PeerClaim) SetStatus(v PeerClaimStatus) {
	o.Status = v
}

// GetOrigin returns the Origin field value
func (o *PeerClaim) GetOrigin() PeerClaimOrigin {
	if o == nil {
		var ret PeerClaimOrigin
		return ret
	}

	return o.Origin
}

// GetOriginOk returns a tuple with the Origin field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetOriginOk() (*PeerClaimOrigin, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Origin, true
}

// SetOrigin sets field value
func (o *PeerClaim) SetOrigin(v PeerClaimOrigin) {
	o.Origin = v
}

// GetConfidence returns the Confidence field value
func (o *PeerClaim) GetConfidence() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetConfidenceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Confidence, true
}

// SetConfidence sets field value
func (o *PeerClaim) SetConfidence(v float32) {
	o.Confidence = v
}

// GetLocked returns the Locked field value
func (o *PeerClaim) GetLocked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Locked
}

// GetLockedOk returns a tuple with the Locked field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetLockedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locked, true
}

// SetLocked sets field value
func (o *PeerClaim) SetLocked(v bool) {
	o.Locked = v
}

// GetProvenance returns the Provenance field value
func (o *PeerClaim) GetProvenance() Provenance {
	if o == nil {
		var ret Provenance
		return ret
	}

	return o.Provenance
}

// GetProvenanceOk returns a tuple with the Provenance field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetProvenanceOk() (*Provenance, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provenance, true
}

// SetProvenance sets field value
func (o *PeerClaim) SetProvenance(v Provenance) {
	o.Provenance = v
}

// GetValidFrom returns the ValidFrom field value
func (o *PeerClaim) GetValidFrom() ValidFrom {
	if o == nil {
		var ret ValidFrom
		return ret
	}

	return o.ValidFrom
}

// GetValidFromOk returns a tuple with the ValidFrom field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetValidFromOk() (*ValidFrom, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidFrom, true
}

// SetValidFrom sets field value
func (o *PeerClaim) SetValidFrom(v ValidFrom) {
	o.ValidFrom = v
}

// GetValidUntil returns the ValidUntil field value
func (o *PeerClaim) GetValidUntil() ValidUntil {
	if o == nil {
		var ret ValidUntil
		return ret
	}

	return o.ValidUntil
}

// GetValidUntilOk returns a tuple with the ValidUntil field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetValidUntilOk() (*ValidUntil, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidUntil, true
}

// SetValidUntil sets field value
func (o *PeerClaim) SetValidUntil(v ValidUntil) {
	o.ValidUntil = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PeerClaim) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PeerClaim) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PeerClaim) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PeerClaim) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *PeerClaim) GetSources() []PeerSource {
	if o == nil || IsNil(o.Sources) {
		var ret []PeerSource
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerClaim) GetSourcesOk() ([]PeerSource, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *PeerClaim) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []PeerSource and assigns it to the Sources field.
func (o *PeerClaim) SetSources(v []PeerSource) {
	o.Sources = v
}

func (o PeerClaim) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerClaim) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["bank_id"] = o.BankId
	toSerialize["model_id"] = o.ModelId
	toSerialize["observer_peer_id"] = o.ObserverPeerId
	toSerialize["target_peer_id"] = o.TargetPeerId
	toSerialize["claim_type"] = o.ClaimType
	toSerialize["text"] = o.Text
	toSerialize["status"] = o.Status
	toSerialize["origin"] = o.Origin
	toSerialize["confidence"] = o.Confidence
	toSerialize["locked"] = o.Locked
	toSerialize["provenance"] = o.Provenance
	toSerialize["valid_from"] = o.ValidFrom
	toSerialize["valid_until"] = o.ValidUntil
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerClaim) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"bank_id",
		"model_id",
		"observer_peer_id",
		"target_peer_id",
		"claim_type",
		"text",
		"status",
		"origin",
		"confidence",
		"locked",
		"provenance",
		"valid_from",
		"valid_until",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerClaim := _PeerClaim{}

	err = json.Unmarshal(data, &varPeerClaim)

	if err != nil {
		return err
	}

	*o = PeerClaim(varPeerClaim)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "bank_id")
		delete(additionalProperties, "model_id")
		delete(additionalProperties, "observer_peer_id")
		delete(additionalProperties, "target_peer_id")
		delete(additionalProperties, "claim_type")
		delete(additionalProperties, "text")
		delete(additionalProperties, "status")
		delete(additionalProperties, "origin")
		delete(additionalProperties, "confidence")
		delete(additionalProperties, "locked")
		delete(additionalProperties, "provenance")
		delete(additionalProperties, "valid_from")
		delete(additionalProperties, "valid_until")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "sources")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerClaim struct {
	value *PeerClaim
	isSet bool
}

func (v NullablePeerClaim) Get() *PeerClaim {
	return v.value
}

func (v *NullablePeerClaim) Set(val *PeerClaim) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerClaim) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerClaim) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerClaim(val *PeerClaim) *NullablePeerClaim {
	return &NullablePeerClaim{value: val, isSet: true}
}

func (v NullablePeerClaim) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerClaim) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


