/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerCardEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerCardEntry{}

// PeerCardEntry Typed compact-card projection of a claim.
type PeerCardEntry struct {
	ClaimId string `json:"claim_id"`
	ClaimType PeerClaimType `json:"claim_type"`
	Text string `json:"text"`
	Confidence float32 `json:"confidence"`
	Locked bool `json:"locked"`
	AdditionalProperties map[string]interface{}
}

type _PeerCardEntry PeerCardEntry

// NewPeerCardEntry instantiates a new PeerCardEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerCardEntry(claimId string, claimType PeerClaimType, text string, confidence float32, locked bool) *PeerCardEntry {
	this := PeerCardEntry{}
	this.ClaimId = claimId
	this.ClaimType = claimType
	this.Text = text
	this.Confidence = confidence
	this.Locked = locked
	return &this
}

// NewPeerCardEntryWithDefaults instantiates a new PeerCardEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerCardEntryWithDefaults() *PeerCardEntry {
	this := PeerCardEntry{}
	return &this
}

// GetClaimId returns the ClaimId field value
func (o *PeerCardEntry) GetClaimId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClaimId
}

// GetClaimIdOk returns a tuple with the ClaimId field value
// and a boolean to check if the value has been set.
func (o *PeerCardEntry) GetClaimIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClaimId, true
}

// SetClaimId sets field value
func (o *PeerCardEntry) SetClaimId(v string) {
	o.ClaimId = v
}

// GetClaimType returns the ClaimType field value
func (o *PeerCardEntry) GetClaimType() PeerClaimType {
	if o == nil {
		var ret PeerClaimType
		return ret
	}

	return o.ClaimType
}

// GetClaimTypeOk returns a tuple with the ClaimType field value
// and a boolean to check if the value has been set.
func (o *PeerCardEntry) GetClaimTypeOk() (*PeerClaimType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClaimType, true
}

// SetClaimType sets field value
func (o *PeerCardEntry) SetClaimType(v PeerClaimType) {
	o.ClaimType = v
}

// GetText returns the Text field value
func (o *PeerCardEntry) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *PeerCardEntry) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *PeerCardEntry) SetText(v string) {
	o.Text = v
}

// GetConfidence returns the Confidence field value
func (o *PeerCardEntry) GetConfidence() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value
// and a boolean to check if the value has been set.
func (o *PeerCardEntry) GetConfidenceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Confidence, true
}

// SetConfidence sets field value
func (o *PeerCardEntry) SetConfidence(v float32) {
	o.Confidence = v
}

// GetLocked returns the Locked field value
func (o *PeerCardEntry) GetLocked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Locked
}

// GetLockedOk returns a tuple with the Locked field value
// and a boolean to check if the value has been set.
func (o *PeerCardEntry) GetLockedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locked, true
}

// SetLocked sets field value
func (o *PeerCardEntry) SetLocked(v bool) {
	o.Locked = v
}

func (o PeerCardEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerCardEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["claim_id"] = o.ClaimId
	toSerialize["claim_type"] = o.ClaimType
	toSerialize["text"] = o.Text
	toSerialize["confidence"] = o.Confidence
	toSerialize["locked"] = o.Locked

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerCardEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"claim_id",
		"claim_type",
		"text",
		"confidence",
		"locked",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerCardEntry := _PeerCardEntry{}

	err = json.Unmarshal(data, &varPeerCardEntry)

	if err != nil {
		return err
	}

	*o = PeerCardEntry(varPeerCardEntry)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "claim_id")
		delete(additionalProperties, "claim_type")
		delete(additionalProperties, "text")
		delete(additionalProperties, "confidence")
		delete(additionalProperties, "locked")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerCardEntry struct {
	value *PeerCardEntry
	isSet bool
}

func (v NullablePeerCardEntry) Get() *PeerCardEntry {
	return v.value
}

func (v *NullablePeerCardEntry) Set(val *PeerCardEntry) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerCardEntry) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerCardEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerCardEntry(val *PeerCardEntry) *NullablePeerCardEntry {
	return &NullablePeerCardEntry{value: val, isSet: true}
}

func (v NullablePeerCardEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerCardEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


