/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerClaimDraft type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerClaimDraft{}

// PeerClaimDraft Caller-supplied claim proposal before origin/status are assigned by the engine.
type PeerClaimDraft struct {
	ClaimType PeerClaimType `json:"claim_type"`
	Text string `json:"text"`
	Confidence *float32 `json:"confidence,omitempty"`
	SourceKind *PeerSourceKind `json:"source_kind,omitempty"`
	SourceIds []string `json:"source_ids,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PeerClaimDraft PeerClaimDraft

// NewPeerClaimDraft instantiates a new PeerClaimDraft object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerClaimDraft(claimType PeerClaimType, text string) *PeerClaimDraft {
	this := PeerClaimDraft{}
	this.ClaimType = claimType
	this.Text = text
	var confidence float32 = 0.7
	this.Confidence = &confidence
	return &this
}

// NewPeerClaimDraftWithDefaults instantiates a new PeerClaimDraft object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerClaimDraftWithDefaults() *PeerClaimDraft {
	this := PeerClaimDraft{}
	var confidence float32 = 0.7
	this.Confidence = &confidence
	return &this
}

// GetClaimType returns the ClaimType field value
func (o *PeerClaimDraft) GetClaimType() PeerClaimType {
	if o == nil {
		var ret PeerClaimType
		return ret
	}

	return o.ClaimType
}

// GetClaimTypeOk returns a tuple with the ClaimType field value
// and a boolean to check if the value has been set.
func (o *PeerClaimDraft) GetClaimTypeOk() (*PeerClaimType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClaimType, true
}

// SetClaimType sets field value
func (o *PeerClaimDraft) SetClaimType(v PeerClaimType) {
	o.ClaimType = v
}

// GetText returns the Text field value
func (o *PeerClaimDraft) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *PeerClaimDraft) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *PeerClaimDraft) SetText(v string) {
	o.Text = v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *PeerClaimDraft) GetConfidence() float32 {
	if o == nil || IsNil(o.Confidence) {
		var ret float32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerClaimDraft) GetConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *PeerClaimDraft) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float32 and assigns it to the Confidence field.
func (o *PeerClaimDraft) SetConfidence(v float32) {
	o.Confidence = &v
}

// GetSourceKind returns the SourceKind field value if set, zero value otherwise.
func (o *PeerClaimDraft) GetSourceKind() PeerSourceKind {
	if o == nil || IsNil(o.SourceKind) {
		var ret PeerSourceKind
		return ret
	}
	return *o.SourceKind
}

// GetSourceKindOk returns a tuple with the SourceKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerClaimDraft) GetSourceKindOk() (*PeerSourceKind, bool) {
	if o == nil || IsNil(o.SourceKind) {
		return nil, false
	}
	return o.SourceKind, true
}

// HasSourceKind returns a boolean if a field has been set.
func (o *PeerClaimDraft) HasSourceKind() bool {
	if o != nil && !IsNil(o.SourceKind) {
		return true
	}

	return false
}

// SetSourceKind gets a reference to the given PeerSourceKind and assigns it to the SourceKind field.
func (o *PeerClaimDraft) SetSourceKind(v PeerSourceKind) {
	o.SourceKind = &v
}

// GetSourceIds returns the SourceIds field value if set, zero value otherwise.
func (o *PeerClaimDraft) GetSourceIds() []string {
	if o == nil || IsNil(o.SourceIds) {
		var ret []string
		return ret
	}
	return o.SourceIds
}

// GetSourceIdsOk returns a tuple with the SourceIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerClaimDraft) GetSourceIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SourceIds) {
		return nil, false
	}
	return o.SourceIds, true
}

// HasSourceIds returns a boolean if a field has been set.
func (o *PeerClaimDraft) HasSourceIds() bool {
	if o != nil && !IsNil(o.SourceIds) {
		return true
	}

	return false
}

// SetSourceIds gets a reference to the given []string and assigns it to the SourceIds field.
func (o *PeerClaimDraft) SetSourceIds(v []string) {
	o.SourceIds = v
}

func (o PeerClaimDraft) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerClaimDraft) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["claim_type"] = o.ClaimType
	toSerialize["text"] = o.Text
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.SourceKind) {
		toSerialize["source_kind"] = o.SourceKind
	}
	if !IsNil(o.SourceIds) {
		toSerialize["source_ids"] = o.SourceIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerClaimDraft) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"claim_type",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerClaimDraft := _PeerClaimDraft{}

	err = json.Unmarshal(data, &varPeerClaimDraft)

	if err != nil {
		return err
	}

	*o = PeerClaimDraft(varPeerClaimDraft)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "claim_type")
		delete(additionalProperties, "text")
		delete(additionalProperties, "confidence")
		delete(additionalProperties, "source_kind")
		delete(additionalProperties, "source_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerClaimDraft struct {
	value *PeerClaimDraft
	isSet bool
}

func (v NullablePeerClaimDraft) Get() *PeerClaimDraft {
	return v.value
}

func (v *NullablePeerClaimDraft) Set(val *PeerClaimDraft) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerClaimDraft) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerClaimDraft) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerClaimDraft(val *PeerClaimDraft) *NullablePeerClaimDraft {
	return &NullablePeerClaimDraft{value: val, isSet: true}
}

func (v NullablePeerClaimDraft) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerClaimDraft) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


