/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerSource{}

// PeerSource One relational provenance edge for a claim.
type PeerSource struct {
	SourceKind PeerSourceKind `json:"source_kind"`
	SourceId string `json:"source_id"`
	AdditionalProperties map[string]interface{}
}

type _PeerSource PeerSource

// NewPeerSource instantiates a new PeerSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerSource(sourceKind PeerSourceKind, sourceId string) *PeerSource {
	this := PeerSource{}
	this.SourceKind = sourceKind
	this.SourceId = sourceId
	return &this
}

// NewPeerSourceWithDefaults instantiates a new PeerSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerSourceWithDefaults() *PeerSource {
	this := PeerSource{}
	return &this
}

// GetSourceKind returns the SourceKind field value
func (o *PeerSource) GetSourceKind() PeerSourceKind {
	if o == nil {
		var ret PeerSourceKind
		return ret
	}

	return o.SourceKind
}

// GetSourceKindOk returns a tuple with the SourceKind field value
// and a boolean to check if the value has been set.
func (o *PeerSource) GetSourceKindOk() (*PeerSourceKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceKind, true
}

// SetSourceKind sets field value
func (o *PeerSource) SetSourceKind(v PeerSourceKind) {
	o.SourceKind = v
}

// GetSourceId returns the SourceId field value
func (o *PeerSource) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *PeerSource) GetSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *PeerSource) SetSourceId(v string) {
	o.SourceId = v
}

func (o PeerSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source_kind"] = o.SourceKind
	toSerialize["source_id"] = o.SourceId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source_kind",
		"source_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerSource := _PeerSource{}

	err = json.Unmarshal(data, &varPeerSource)

	if err != nil {
		return err
	}

	*o = PeerSource(varPeerSource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "source_kind")
		delete(additionalProperties, "source_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerSource struct {
	value *PeerSource
	isSet bool
}

func (v NullablePeerSource) Get() *PeerSource {
	return v.value
}

func (v *NullablePeerSource) Set(val *PeerSource) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerSource) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerSource(val *PeerSource) *NullablePeerSource {
	return &NullablePeerSource{value: val, isSet: true}
}

func (v NullablePeerSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


