/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the PeerModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerModel{}

// PeerModel Materialized directional model without untyped card payloads.
type PeerModel struct {
	Id string `json:"id"`
	BankId string `json:"bank_id"`
	ObserverPeerId string `json:"observer_peer_id"`
	TargetPeerId string `json:"target_peer_id"`
	Version int32 `json:"version"`
	Card PeerCard `json:"card"`
	Representation string `json:"representation"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	SourceCursor *SourceCursor `json:"source_cursor,omitempty"`
	SourceCursorId *SourceCursorId `json:"source_cursor_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PeerModel PeerModel

// NewPeerModel instantiates a new PeerModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerModel(id string, bankId string, observerPeerId string, targetPeerId string, version int32, card PeerCard, representation string, createdAt time.Time, updatedAt time.Time) *PeerModel {
	this := PeerModel{}
	this.Id = id
	this.BankId = bankId
	this.ObserverPeerId = observerPeerId
	this.TargetPeerId = targetPeerId
	this.Version = version
	this.Card = card
	this.Representation = representation
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewPeerModelWithDefaults instantiates a new PeerModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerModelWithDefaults() *PeerModel {
	this := PeerModel{}
	return &this
}

// GetId returns the Id field value
func (o *PeerModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PeerModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PeerModel) SetId(v string) {
	o.Id = v
}

// GetBankId returns the BankId field value
func (o *PeerModel) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *PeerModel) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *PeerModel) SetBankId(v string) {
	o.BankId = v
}

// GetObserverPeerId returns the ObserverPeerId field value
func (o *PeerModel) GetObserverPeerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObserverPeerId
}

// GetObserverPeerIdOk returns a tuple with the ObserverPeerId field value
// and a boolean to check if the value has been set.
func (o *PeerModel) GetObserverPeerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObserverPeerId, true
}

// SetObserverPeerId sets field value
func (o *PeerModel) SetObserverPeerId(v string) {
	o.ObserverPeerId = v
}

// GetTargetPeerId returns the TargetPeerId field value
func (o *PeerModel) GetTargetPeerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetPeerId
}

// GetTargetPeerIdOk returns a tuple with the TargetPeerId field value
// and a boolean to check if the value has been set.
func (o *PeerModel) GetTargetPeerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetPeerId, true
}

// SetTargetPeerId sets field value
func (o *PeerModel) SetTargetPeerId(v string) {
	o.TargetPeerId = v
}

// GetVersion returns the Version field value
func (o *PeerModel) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *PeerModel) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *PeerModel) SetVersion(v int32) {
	o.Version = v
}

// GetCard returns the Card field value
func (o *PeerModel) GetCard() PeerCard {
	if o == nil {
		var ret PeerCard
		return ret
	}

	return o.Card
}

// GetCardOk returns a tuple with the Card field value
// and a boolean to check if the value has been set.
func (o *PeerModel) GetCardOk() (*PeerCard, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Card, true
}

// SetCard sets field value
func (o *PeerModel) SetCard(v PeerCard) {
	o.Card = v
}

// GetRepresentation returns the Representation field value
func (o *PeerModel) GetRepresentation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Representation
}

// GetRepresentationOk returns a tuple with the Representation field value
// and a boolean to check if the value has been set.
func (o *PeerModel) GetRepresentationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Representation, true
}

// SetRepresentation sets field value
func (o *PeerModel) SetRepresentation(v string) {
	o.Representation = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PeerModel) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PeerModel) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PeerModel) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PeerModel) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PeerModel) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PeerModel) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetSourceCursor returns the SourceCursor field value if set, zero value otherwise.
func (o *PeerModel) GetSourceCursor() SourceCursor {
	if o == nil || IsNil(o.SourceCursor) {
		var ret SourceCursor
		return ret
	}
	return *o.SourceCursor
}

// GetSourceCursorOk returns a tuple with the SourceCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerModel) GetSourceCursorOk() (*SourceCursor, bool) {
	if o == nil || IsNil(o.SourceCursor) {
		return nil, false
	}
	return o.SourceCursor, true
}

// HasSourceCursor returns a boolean if a field has been set.
func (o *PeerModel) HasSourceCursor() bool {
	if o != nil && !IsNil(o.SourceCursor) {
		return true
	}

	return false
}

// SetSourceCursor gets a reference to the given SourceCursor and assigns it to the SourceCursor field.
func (o *PeerModel) SetSourceCursor(v SourceCursor) {
	o.SourceCursor = &v
}

// GetSourceCursorId returns the SourceCursorId field value if set, zero value otherwise.
func (o *PeerModel) GetSourceCursorId() SourceCursorId {
	if o == nil || IsNil(o.SourceCursorId) {
		var ret SourceCursorId
		return ret
	}
	return *o.SourceCursorId
}

// GetSourceCursorIdOk returns a tuple with the SourceCursorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerModel) GetSourceCursorIdOk() (*SourceCursorId, bool) {
	if o == nil || IsNil(o.SourceCursorId) {
		return nil, false
	}
	return o.SourceCursorId, true
}

// HasSourceCursorId returns a boolean if a field has been set.
func (o *PeerModel) HasSourceCursorId() bool {
	if o != nil && !IsNil(o.SourceCursorId) {
		return true
	}

	return false
}

// SetSourceCursorId gets a reference to the given SourceCursorId and assigns it to the SourceCursorId field.
func (o *PeerModel) SetSourceCursorId(v SourceCursorId) {
	o.SourceCursorId = &v
}

func (o PeerModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["bank_id"] = o.BankId
	toSerialize["observer_peer_id"] = o.ObserverPeerId
	toSerialize["target_peer_id"] = o.TargetPeerId
	toSerialize["version"] = o.Version
	toSerialize["card"] = o.Card
	toSerialize["representation"] = o.Representation
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.SourceCursor) {
		toSerialize["source_cursor"] = o.SourceCursor
	}
	if !IsNil(o.SourceCursorId) {
		toSerialize["source_cursor_id"] = o.SourceCursorId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"bank_id",
		"observer_peer_id",
		"target_peer_id",
		"version",
		"card",
		"representation",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerModel := _PeerModel{}

	err = json.Unmarshal(data, &varPeerModel)

	if err != nil {
		return err
	}

	*o = PeerModel(varPeerModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "bank_id")
		delete(additionalProperties, "observer_peer_id")
		delete(additionalProperties, "target_peer_id")
		delete(additionalProperties, "version")
		delete(additionalProperties, "card")
		delete(additionalProperties, "representation")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "source_cursor")
		delete(additionalProperties, "source_cursor_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerModel struct {
	value *PeerModel
	isSet bool
}

func (v NullablePeerModel) Get() *PeerModel {
	return v.value
}

func (v *NullablePeerModel) Set(val *PeerModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerModel(val *PeerModel) *NullablePeerModel {
	return &NullablePeerModel{value: val, isSet: true}
}

func (v NullablePeerModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


