/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// PeerSourceKind Portable source-link namespaces supported by the first slice.
type PeerSourceKind string

// List of PeerSourceKind
const (
	PeerSourceKindMemoryUnit PeerSourceKind = "memory_unit"
	PeerSourceKindManual PeerSourceKind = "manual"
)

// All allowed values of PeerSourceKind enum
var AllowedPeerSourceKindEnumValues = []PeerSourceKind{
	"memory_unit",
	"manual",
}

func (v *PeerSourceKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PeerSourceKind(value)
	for _, existing := range AllowedPeerSourceKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PeerSourceKind", value)
}

// NewPeerSourceKindFromValue returns a pointer to a valid PeerSourceKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPeerSourceKindFromValue(v string) (*PeerSourceKind, error) {
	ev := PeerSourceKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PeerSourceKind: valid values are %v", v, AllowedPeerSourceKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PeerSourceKind) IsValid() bool {
	for _, existing := range AllowedPeerSourceKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PeerSourceKind value
func (v PeerSourceKind) Ptr() *PeerSourceKind {
	return &v
}

type NullablePeerSourceKind struct {
	value *PeerSourceKind
	isSet bool
}

func (v NullablePeerSourceKind) Get() *PeerSourceKind {
	return v.value
}

func (v *NullablePeerSourceKind) Set(val *PeerSourceKind) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerSourceKind) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerSourceKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerSourceKind(val *PeerSourceKind) *NullablePeerSourceKind {
	return &NullablePeerSourceKind{value: val, isSet: true}
}

func (v NullablePeerSourceKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerSourceKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

