/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerContext{}

// PeerContext Typed context projection used by callers before a future retain seam exists.
type PeerContext struct {
	BankId string `json:"bank_id"`
	ObserverPeerId string `json:"observer_peer_id"`
	TargetPeerId string `json:"target_peer_id"`
	ModelId string `json:"model_id"`
	Version int32 `json:"version"`
	Card PeerCard `json:"card"`
	Representation string `json:"representation"`
	Claims []PeerClaim `json:"claims,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PeerContext PeerContext

// NewPeerContext instantiates a new PeerContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerContext(bankId string, observerPeerId string, targetPeerId string, modelId string, version int32, card PeerCard, representation string) *PeerContext {
	this := PeerContext{}
	this.BankId = bankId
	this.ObserverPeerId = observerPeerId
	this.TargetPeerId = targetPeerId
	this.ModelId = modelId
	this.Version = version
	this.Card = card
	this.Representation = representation
	return &this
}

// NewPeerContextWithDefaults instantiates a new PeerContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerContextWithDefaults() *PeerContext {
	this := PeerContext{}
	return &this
}

// GetBankId returns the BankId field value
func (o *PeerContext) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *PeerContext) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *PeerContext) SetBankId(v string) {
	o.BankId = v
}

// GetObserverPeerId returns the ObserverPeerId field value
func (o *PeerContext) GetObserverPeerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObserverPeerId
}

// GetObserverPeerIdOk returns a tuple with the ObserverPeerId field value
// and a boolean to check if the value has been set.
func (o *PeerContext) GetObserverPeerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObserverPeerId, true
}

// SetObserverPeerId sets field value
func (o *PeerContext) SetObserverPeerId(v string) {
	o.ObserverPeerId = v
}

// GetTargetPeerId returns the TargetPeerId field value
func (o *PeerContext) GetTargetPeerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetPeerId
}

// GetTargetPeerIdOk returns a tuple with the TargetPeerId field value
// and a boolean to check if the value has been set.
func (o *PeerContext) GetTargetPeerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetPeerId, true
}

// SetTargetPeerId sets field value
func (o *PeerContext) SetTargetPeerId(v string) {
	o.TargetPeerId = v
}

// GetModelId returns the ModelId field value
func (o *PeerContext) GetModelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModelId
}

// GetModelIdOk returns a tuple with the ModelId field value
// and a boolean to check if the value has been set.
func (o *PeerContext) GetModelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelId, true
}

// SetModelId sets field value
func (o *PeerContext) SetModelId(v string) {
	o.ModelId = v
}

// GetVersion returns the Version field value
func (o *PeerContext) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *PeerContext) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *PeerContext) SetVersion(v int32) {
	o.Version = v
}

// GetCard returns the Card field value
func (o *PeerContext) GetCard() PeerCard {
	if o == nil {
		var ret PeerCard
		return ret
	}

	return o.Card
}

// GetCardOk returns a tuple with the Card field value
// and a boolean to check if the value has been set.
func (o *PeerContext) GetCardOk() (*PeerCard, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Card, true
}

// SetCard sets field value
func (o *PeerContext) SetCard(v PeerCard) {
	o.Card = v
}

// GetRepresentation returns the Representation field value
func (o *PeerContext) GetRepresentation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Representation
}

// GetRepresentationOk returns a tuple with the Representation field value
// and a boolean to check if the value has been set.
func (o *PeerContext) GetRepresentationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Representation, true
}

// SetRepresentation sets field value
func (o *PeerContext) SetRepresentation(v string) {
	o.Representation = v
}

// GetClaims returns the Claims field value if set, zero value otherwise.
func (o *PeerContext) GetClaims() []PeerClaim {
	if o == nil || IsNil(o.Claims) {
		var ret []PeerClaim
		return ret
	}
	return o.Claims
}

// GetClaimsOk returns a tuple with the Claims field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerContext) GetClaimsOk() ([]PeerClaim, bool) {
	if o == nil || IsNil(o.Claims) {
		return nil, false
	}
	return o.Claims, true
}

// HasClaims returns a boolean if a field has been set.
func (o *PeerContext) HasClaims() bool {
	if o != nil && !IsNil(o.Claims) {
		return true
	}

	return false
}

// SetClaims gets a reference to the given []PeerClaim and assigns it to the Claims field.
func (o *PeerContext) SetClaims(v []PeerClaim) {
	o.Claims = v
}

func (o PeerContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank_id"] = o.BankId
	toSerialize["observer_peer_id"] = o.ObserverPeerId
	toSerialize["target_peer_id"] = o.TargetPeerId
	toSerialize["model_id"] = o.ModelId
	toSerialize["version"] = o.Version
	toSerialize["card"] = o.Card
	toSerialize["representation"] = o.Representation
	if !IsNil(o.Claims) {
		toSerialize["claims"] = o.Claims
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerContext) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
		"observer_peer_id",
		"target_peer_id",
		"model_id",
		"version",
		"card",
		"representation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerContext := _PeerContext{}

	err = json.Unmarshal(data, &varPeerContext)

	if err != nil {
		return err
	}

	*o = PeerContext(varPeerContext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bank_id")
		delete(additionalProperties, "observer_peer_id")
		delete(additionalProperties, "target_peer_id")
		delete(additionalProperties, "model_id")
		delete(additionalProperties, "version")
		delete(additionalProperties, "card")
		delete(additionalProperties, "representation")
		delete(additionalProperties, "claims")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerContext struct {
	value *PeerContext
	isSet bool
}

func (v NullablePeerContext) Get() *PeerContext {
	return v.value
}

func (v *NullablePeerContext) Set(val *PeerContext) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerContext) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerContext(val *PeerContext) *NullablePeerContext {
	return &NullablePeerContext{value: val, isSet: true}
}

func (v NullablePeerContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


