/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// PeerClaimStatus Lifecycle state of an atomic peer claim.
type PeerClaimStatus string

// List of PeerClaimStatus
const (
	PeerClaimStatusActive PeerClaimStatus = "active"
	PeerClaimStatusSuperseded PeerClaimStatus = "superseded"
	PeerClaimStatusContested PeerClaimStatus = "contested"
	PeerClaimStatusRetracted PeerClaimStatus = "retracted"
)

// All allowed values of PeerClaimStatus enum
var AllowedPeerClaimStatusEnumValues = []PeerClaimStatus{
	"active",
	"superseded",
	"contested",
	"retracted",
}

func (v *PeerClaimStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PeerClaimStatus(value)
	for _, existing := range AllowedPeerClaimStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PeerClaimStatus", value)
}

// NewPeerClaimStatusFromValue returns a pointer to a valid PeerClaimStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPeerClaimStatusFromValue(v string) (*PeerClaimStatus, error) {
	ev := PeerClaimStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PeerClaimStatus: valid values are %v", v, AllowedPeerClaimStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PeerClaimStatus) IsValid() bool {
	for _, existing := range AllowedPeerClaimStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PeerClaimStatus value
func (v PeerClaimStatus) Ptr() *PeerClaimStatus {
	return &v
}

type NullablePeerClaimStatus struct {
	value *PeerClaimStatus
	isSet bool
}

func (v NullablePeerClaimStatus) Get() *PeerClaimStatus {
	return v.value
}

func (v *NullablePeerClaimStatus) Set(val *PeerClaimStatus) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerClaimStatus) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerClaimStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerClaimStatus(val *PeerClaimStatus) *NullablePeerClaimStatus {
	return &NullablePeerClaimStatus{value: val, isSet: true}
}

func (v NullablePeerClaimStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerClaimStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

