/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)


// SourceCursorId struct for SourceCursorId
type SourceCursorId struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SourceCursorId) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SourceCursorId)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *SourceCursorId) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableSourceCursorId struct {
	value *SourceCursorId
	isSet bool
}

func (v NullableSourceCursorId) Get() *SourceCursorId {
	return v.value
}

func (v *NullableSourceCursorId) Set(val *SourceCursorId) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceCursorId) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceCursorId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceCursorId(val *SourceCursorId) *NullableSourceCursorId {
	return &NullableSourceCursorId{value: val, isSet: true}
}

func (v NullableSourceCursorId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceCursorId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


