/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the PeerList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerList{}

// PeerList Paginated peer collection.
type PeerList struct {
	Items []Peer `json:"items,omitempty"`
	Total int32 `json:"total"`
	Limit int32 `json:"limit"`
	Offset int32 `json:"offset"`
	AdditionalProperties map[string]interface{}
}

type _PeerList PeerList

// NewPeerList instantiates a new PeerList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerList(total int32, limit int32, offset int32) *PeerList {
	this := PeerList{}
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewPeerListWithDefaults instantiates a new PeerList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerListWithDefaults() *PeerList {
	this := PeerList{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PeerList) GetItems() []Peer {
	if o == nil || IsNil(o.Items) {
		var ret []Peer
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerList) GetItemsOk() ([]Peer, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PeerList) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Peer and assigns it to the Items field.
func (o *PeerList) SetItems(v []Peer) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *PeerList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *PeerList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *PeerList) SetTotal(v int32) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *PeerList) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *PeerList) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *PeerList) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *PeerList) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *PeerList) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *PeerList) SetOffset(v int32) {
	o.Offset = v
}

func (o PeerList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"limit",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerList := _PeerList{}

	err = json.Unmarshal(data, &varPeerList)

	if err != nil {
		return err
	}

	*o = PeerList(varPeerList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "total")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "offset")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerList struct {
	value *PeerList
	isSet bool
}

func (v NullablePeerList) Get() *PeerList {
	return v.value
}

func (v *NullablePeerList) Set(val *PeerList) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerList) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerList(val *PeerList) *NullablePeerList {
	return &NullablePeerList{value: val, isSet: true}
}

func (v NullablePeerList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


