/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the PeerCard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PeerCard{}

// PeerCard Stable, compact projection limited to the four allowed claim types.
type PeerCard struct {
	ModelId string `json:"model_id"`
	BankId string `json:"bank_id"`
	ObserverPeerId string `json:"observer_peer_id"`
	TargetPeerId string `json:"target_peer_id"`
	Version int32 `json:"version"`
	Entries []PeerCardEntry `json:"entries,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
	AdditionalProperties map[string]interface{}
}

type _PeerCard PeerCard

// NewPeerCard instantiates a new PeerCard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeerCard(modelId string, bankId string, observerPeerId string, targetPeerId string, version int32, updatedAt time.Time) *PeerCard {
	this := PeerCard{}
	this.ModelId = modelId
	this.BankId = bankId
	this.ObserverPeerId = observerPeerId
	this.TargetPeerId = targetPeerId
	this.Version = version
	this.UpdatedAt = updatedAt
	return &this
}

// NewPeerCardWithDefaults instantiates a new PeerCard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeerCardWithDefaults() *PeerCard {
	this := PeerCard{}
	return &this
}

// GetModelId returns the ModelId field value
func (o *PeerCard) GetModelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModelId
}

// GetModelIdOk returns a tuple with the ModelId field value
// and a boolean to check if the value has been set.
func (o *PeerCard) GetModelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelId, true
}

// SetModelId sets field value
func (o *PeerCard) SetModelId(v string) {
	o.ModelId = v
}

// GetBankId returns the BankId field value
func (o *PeerCard) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *PeerCard) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *PeerCard) SetBankId(v string) {
	o.BankId = v
}

// GetObserverPeerId returns the ObserverPeerId field value
func (o *PeerCard) GetObserverPeerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObserverPeerId
}

// GetObserverPeerIdOk returns a tuple with the ObserverPeerId field value
// and a boolean to check if the value has been set.
func (o *PeerCard) GetObserverPeerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObserverPeerId, true
}

// SetObserverPeerId sets field value
func (o *PeerCard) SetObserverPeerId(v string) {
	o.ObserverPeerId = v
}

// GetTargetPeerId returns the TargetPeerId field value
func (o *PeerCard) GetTargetPeerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetPeerId
}

// GetTargetPeerIdOk returns a tuple with the TargetPeerId field value
// and a boolean to check if the value has been set.
func (o *PeerCard) GetTargetPeerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetPeerId, true
}

// SetTargetPeerId sets field value
func (o *PeerCard) SetTargetPeerId(v string) {
	o.TargetPeerId = v
}

// GetVersion returns the Version field value
func (o *PeerCard) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *PeerCard) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *PeerCard) SetVersion(v int32) {
	o.Version = v
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *PeerCard) GetEntries() []PeerCardEntry {
	if o == nil || IsNil(o.Entries) {
		var ret []PeerCardEntry
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeerCard) GetEntriesOk() ([]PeerCardEntry, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *PeerCard) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []PeerCardEntry and assigns it to the Entries field.
func (o *PeerCard) SetEntries(v []PeerCardEntry) {
	o.Entries = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PeerCard) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PeerCard) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PeerCard) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o PeerCard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PeerCard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["model_id"] = o.ModelId
	toSerialize["bank_id"] = o.BankId
	toSerialize["observer_peer_id"] = o.ObserverPeerId
	toSerialize["target_peer_id"] = o.TargetPeerId
	toSerialize["version"] = o.Version
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	toSerialize["updated_at"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PeerCard) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"model_id",
		"bank_id",
		"observer_peer_id",
		"target_peer_id",
		"version",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPeerCard := _PeerCard{}

	err = json.Unmarshal(data, &varPeerCard)

	if err != nil {
		return err
	}

	*o = PeerCard(varPeerCard)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "model_id")
		delete(additionalProperties, "bank_id")
		delete(additionalProperties, "observer_peer_id")
		delete(additionalProperties, "target_peer_id")
		delete(additionalProperties, "version")
		delete(additionalProperties, "entries")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePeerCard struct {
	value *PeerCard
	isSet bool
}

func (v NullablePeerCard) Get() *PeerCard {
	return v.value
}

func (v *NullablePeerCard) Set(val *PeerCard) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerCard) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerCard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerCard(val *PeerCard) *NullablePeerCard {
	return &NullablePeerCard{value: val, isSet: true}
}

func (v NullablePeerCard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerCard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


