/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
	"fmt"
)


// ValidUntil struct for ValidUntil
type ValidUntil struct {
	TimeTime *time.Time
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ValidUntil) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into TimeTime
	err = json.Unmarshal(data, &dst.TimeTime);
	if err == nil {
		jsonTimeTime, _ := json.Marshal(dst.TimeTime)
		if string(jsonTimeTime) == "{}" { // empty struct
			dst.TimeTime = nil
		} else {
			return nil // data stored in dst.TimeTime, return on the first match
		}
	} else {
		dst.TimeTime = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ValidUntil)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ValidUntil) MarshalJSON() ([]byte, error) {
	if src.TimeTime != nil {
		return json.Marshal(&src.TimeTime)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableValidUntil struct {
	value *ValidUntil
	isSet bool
}

func (v NullableValidUntil) Get() *ValidUntil {
	return v.value
}

func (v *NullableValidUntil) Set(val *ValidUntil) {
	v.value = val
	v.isSet = true
}

func (v NullableValidUntil) IsSet() bool {
	return v.isSet
}

func (v *NullableValidUntil) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidUntil(val *ValidUntil) *NullableValidUntil {
	return &NullableValidUntil{value: val, isSet: true}
}

func (v NullableValidUntil) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidUntil) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


