/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// PeerClaimOrigin How a claim entered the model.
type PeerClaimOrigin string

// List of PeerClaimOrigin
const (
	PeerClaimOriginDerived PeerClaimOrigin = "derived"
	PeerClaimOriginManual PeerClaimOrigin = "manual"
	PeerClaimOriginImported PeerClaimOrigin = "imported"
)

// All allowed values of PeerClaimOrigin enum
var AllowedPeerClaimOriginEnumValues = []PeerClaimOrigin{
	"derived",
	"manual",
	"imported",
}

func (v *PeerClaimOrigin) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PeerClaimOrigin(value)
	for _, existing := range AllowedPeerClaimOriginEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PeerClaimOrigin", value)
}

// NewPeerClaimOriginFromValue returns a pointer to a valid PeerClaimOrigin
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPeerClaimOriginFromValue(v string) (*PeerClaimOrigin, error) {
	ev := PeerClaimOrigin(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PeerClaimOrigin: valid values are %v", v, AllowedPeerClaimOriginEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PeerClaimOrigin) IsValid() bool {
	for _, existing := range AllowedPeerClaimOriginEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PeerClaimOrigin value
func (v PeerClaimOrigin) Ptr() *PeerClaimOrigin {
	return &v
}

type NullablePeerClaimOrigin struct {
	value *PeerClaimOrigin
	isSet bool
}

func (v NullablePeerClaimOrigin) Get() *PeerClaimOrigin {
	return v.value
}

func (v *NullablePeerClaimOrigin) Set(val *PeerClaimOrigin) {
	v.value = val
	v.isSet = true
}

func (v NullablePeerClaimOrigin) IsSet() bool {
	return v.isSet
}

func (v *NullablePeerClaimOrigin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeerClaimOrigin(val *PeerClaimOrigin) *NullablePeerClaimOrigin {
	return &NullablePeerClaimOrigin{value: val, isSet: true}
}

func (v NullablePeerClaimOrigin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeerClaimOrigin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

