/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the RetainPeerContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetainPeerContext{}

// RetainPeerContext Explicit participant attribution carried through retain.  IDs may be either a peer's internal ``id`` or its bank-scoped ``external_id``. This metadata is declarative input; Hindsight does not infer speaker or subject identity from free-form text at the HTTP boundary.
type RetainPeerContext struct {
	ObserverPeerId *ObserverPeerId `json:"observer_peer_id,omitempty"`
	SpeakerPeerId *SpeakerPeerId `json:"speaker_peer_id,omitempty"`
	SubjectPeerIds []string `json:"subject_peer_ids,omitempty"`
	ParticipantPeerIds []string `json:"participant_peer_ids,omitempty"`
	SourceMessageId *SourceMessageId `json:"source_message_id,omitempty"`
	SessionId *SessionId `json:"session_id,omitempty"`
	Modality *string `json:"modality,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RetainPeerContext RetainPeerContext

// NewRetainPeerContext instantiates a new RetainPeerContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetainPeerContext() *RetainPeerContext {
	this := RetainPeerContext{}
	var modality string = "actual"
	this.Modality = &modality
	return &this
}

// NewRetainPeerContextWithDefaults instantiates a new RetainPeerContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetainPeerContextWithDefaults() *RetainPeerContext {
	this := RetainPeerContext{}
	var modality string = "actual"
	this.Modality = &modality
	return &this
}

// GetObserverPeerId returns the ObserverPeerId field value if set, zero value otherwise.
func (o *RetainPeerContext) GetObserverPeerId() ObserverPeerId {
	if o == nil || IsNil(o.ObserverPeerId) {
		var ret ObserverPeerId
		return ret
	}
	return *o.ObserverPeerId
}

// GetObserverPeerIdOk returns a tuple with the ObserverPeerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetainPeerContext) GetObserverPeerIdOk() (*ObserverPeerId, bool) {
	if o == nil || IsNil(o.ObserverPeerId) {
		return nil, false
	}
	return o.ObserverPeerId, true
}

// HasObserverPeerId returns a boolean if a field has been set.
func (o *RetainPeerContext) HasObserverPeerId() bool {
	if o != nil && !IsNil(o.ObserverPeerId) {
		return true
	}

	return false
}

// SetObserverPeerId gets a reference to the given ObserverPeerId and assigns it to the ObserverPeerId field.
func (o *RetainPeerContext) SetObserverPeerId(v ObserverPeerId) {
	o.ObserverPeerId = &v
}

// GetSpeakerPeerId returns the SpeakerPeerId field value if set, zero value otherwise.
func (o *RetainPeerContext) GetSpeakerPeerId() SpeakerPeerId {
	if o == nil || IsNil(o.SpeakerPeerId) {
		var ret SpeakerPeerId
		return ret
	}
	return *o.SpeakerPeerId
}

// GetSpeakerPeerIdOk returns a tuple with the SpeakerPeerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetainPeerContext) GetSpeakerPeerIdOk() (*SpeakerPeerId, bool) {
	if o == nil || IsNil(o.SpeakerPeerId) {
		return nil, false
	}
	return o.SpeakerPeerId, true
}

// HasSpeakerPeerId returns a boolean if a field has been set.
func (o *RetainPeerContext) HasSpeakerPeerId() bool {
	if o != nil && !IsNil(o.SpeakerPeerId) {
		return true
	}

	return false
}

// SetSpeakerPeerId gets a reference to the given SpeakerPeerId and assigns it to the SpeakerPeerId field.
func (o *RetainPeerContext) SetSpeakerPeerId(v SpeakerPeerId) {
	o.SpeakerPeerId = &v
}

// GetSubjectPeerIds returns the SubjectPeerIds field value if set, zero value otherwise.
func (o *RetainPeerContext) GetSubjectPeerIds() []string {
	if o == nil || IsNil(o.SubjectPeerIds) {
		var ret []string
		return ret
	}
	return o.SubjectPeerIds
}

// GetSubjectPeerIdsOk returns a tuple with the SubjectPeerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetainPeerContext) GetSubjectPeerIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SubjectPeerIds) {
		return nil, false
	}
	return o.SubjectPeerIds, true
}

// HasSubjectPeerIds returns a boolean if a field has been set.
func (o *RetainPeerContext) HasSubjectPeerIds() bool {
	if o != nil && !IsNil(o.SubjectPeerIds) {
		return true
	}

	return false
}

// SetSubjectPeerIds gets a reference to the given []string and assigns it to the SubjectPeerIds field.
func (o *RetainPeerContext) SetSubjectPeerIds(v []string) {
	o.SubjectPeerIds = v
}

// GetParticipantPeerIds returns the ParticipantPeerIds field value if set, zero value otherwise.
func (o *RetainPeerContext) GetParticipantPeerIds() []string {
	if o == nil || IsNil(o.ParticipantPeerIds) {
		var ret []string
		return ret
	}
	return o.ParticipantPeerIds
}

// GetParticipantPeerIdsOk returns a tuple with the ParticipantPeerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetainPeerContext) GetParticipantPeerIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ParticipantPeerIds) {
		return nil, false
	}
	return o.ParticipantPeerIds, true
}

// HasParticipantPeerIds returns a boolean if a field has been set.
func (o *RetainPeerContext) HasParticipantPeerIds() bool {
	if o != nil && !IsNil(o.ParticipantPeerIds) {
		return true
	}

	return false
}

// SetParticipantPeerIds gets a reference to the given []string and assigns it to the ParticipantPeerIds field.
func (o *RetainPeerContext) SetParticipantPeerIds(v []string) {
	o.ParticipantPeerIds = v
}

// GetSourceMessageId returns the SourceMessageId field value if set, zero value otherwise.
func (o *RetainPeerContext) GetSourceMessageId() SourceMessageId {
	if o == nil || IsNil(o.SourceMessageId) {
		var ret SourceMessageId
		return ret
	}
	return *o.SourceMessageId
}

// GetSourceMessageIdOk returns a tuple with the SourceMessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetainPeerContext) GetSourceMessageIdOk() (*SourceMessageId, bool) {
	if o == nil || IsNil(o.SourceMessageId) {
		return nil, false
	}
	return o.SourceMessageId, true
}

// HasSourceMessageId returns a boolean if a field has been set.
func (o *RetainPeerContext) HasSourceMessageId() bool {
	if o != nil && !IsNil(o.SourceMessageId) {
		return true
	}

	return false
}

// SetSourceMessageId gets a reference to the given SourceMessageId and assigns it to the SourceMessageId field.
func (o *RetainPeerContext) SetSourceMessageId(v SourceMessageId) {
	o.SourceMessageId = &v
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *RetainPeerContext) GetSessionId() SessionId {
	if o == nil || IsNil(o.SessionId) {
		var ret SessionId
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetainPeerContext) GetSessionIdOk() (*SessionId, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *RetainPeerContext) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given SessionId and assigns it to the SessionId field.
func (o *RetainPeerContext) SetSessionId(v SessionId) {
	o.SessionId = &v
}

// GetModality returns the Modality field value if set, zero value otherwise.
func (o *RetainPeerContext) GetModality() string {
	if o == nil || IsNil(o.Modality) {
		var ret string
		return ret
	}
	return *o.Modality
}

// GetModalityOk returns a tuple with the Modality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetainPeerContext) GetModalityOk() (*string, bool) {
	if o == nil || IsNil(o.Modality) {
		return nil, false
	}
	return o.Modality, true
}

// HasModality returns a boolean if a field has been set.
func (o *RetainPeerContext) HasModality() bool {
	if o != nil && !IsNil(o.Modality) {
		return true
	}

	return false
}

// SetModality gets a reference to the given string and assigns it to the Modality field.
func (o *RetainPeerContext) SetModality(v string) {
	o.Modality = &v
}

func (o RetainPeerContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetainPeerContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObserverPeerId) {
		toSerialize["observer_peer_id"] = o.ObserverPeerId
	}
	if !IsNil(o.SpeakerPeerId) {
		toSerialize["speaker_peer_id"] = o.SpeakerPeerId
	}
	if !IsNil(o.SubjectPeerIds) {
		toSerialize["subject_peer_ids"] = o.SubjectPeerIds
	}
	if !IsNil(o.ParticipantPeerIds) {
		toSerialize["participant_peer_ids"] = o.ParticipantPeerIds
	}
	if !IsNil(o.SourceMessageId) {
		toSerialize["source_message_id"] = o.SourceMessageId
	}
	if !IsNil(o.SessionId) {
		toSerialize["session_id"] = o.SessionId
	}
	if !IsNil(o.Modality) {
		toSerialize["modality"] = o.Modality
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RetainPeerContext) UnmarshalJSON(data []byte) (err error) {
	varRetainPeerContext := _RetainPeerContext{}

	err = json.Unmarshal(data, &varRetainPeerContext)

	if err != nil {
		return err
	}

	*o = RetainPeerContext(varRetainPeerContext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "observer_peer_id")
		delete(additionalProperties, "speaker_peer_id")
		delete(additionalProperties, "subject_peer_ids")
		delete(additionalProperties, "participant_peer_ids")
		delete(additionalProperties, "source_message_id")
		delete(additionalProperties, "session_id")
		delete(additionalProperties, "modality")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRetainPeerContext struct {
	value *RetainPeerContext
	isSet bool
}

func (v NullableRetainPeerContext) Get() *RetainPeerContext {
	return v.value
}

func (v *NullableRetainPeerContext) Set(val *RetainPeerContext) {
	v.value = val
	v.isSet = true
}

func (v NullableRetainPeerContext) IsSet() bool {
	return v.isSet
}

func (v *NullableRetainPeerContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetainPeerContext(val *RetainPeerContext) *NullableRetainPeerContext {
	return &NullableRetainPeerContext{value: val, isSet: true}
}

func (v NullableRetainPeerContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetainPeerContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


